import { Document } from '../entities';

export class DocumentResponseDto {
  id: number;
  documentKey: string;
  documentName: string;
  documentType: string;
  documentCategory: string | null;
  fileName: string;
  filePath: string;
  fileSize: number;
  mimeType: string | null;
  fileExtension: string | null;
  currentVersion: number;
  versionCount: number;
  isLatestVersion: boolean;
  parentDocumentId: number | null;
  folderPath: string | null;
  description: string | null;
  content: string | null;
  contentSummary: string | null;
  tags: string[] | null;
  labels: string[] | null;
  customFields: Record<string, any> | null;
  documentStatus: string;
  documentStage: string | null;
  ownerId: number;
  organizationId: number | null;
  isPublic: boolean;
  isShared: boolean;
  sharingEnabled: boolean;
  templateId: number | null;
  entityType: string | null;
  entityId: number | null;
  storageProvider: string;
  storageLocation: string | null;
  isEncrypted: boolean;
  isPasswordProtected: boolean;
  isIndexed: boolean;
  metadata: Record<string, any> | null;
  createdAt: Date;
  updatedAt: Date;
  createdBy: number;
  updatedBy: number | null;

  static fromEntity(entity: Document): DocumentResponseDto {
    const dto = new DocumentResponseDto();
    dto.id = entity.id;
    dto.documentKey = entity.documentKey;
    dto.documentName = entity.documentName;
    dto.documentType = entity.documentType;
    dto.documentCategory = entity.documentCategory;
    dto.fileName = entity.fileName;
    dto.filePath = entity.filePath;
    dto.fileSize = entity.fileSize;
    dto.mimeType = entity.mimeType;
    dto.fileExtension = entity.fileExtension;
    dto.currentVersion = entity.currentVersion;
    dto.versionCount = entity.versionCount;
    dto.isLatestVersion = entity.isLatestVersion;
    dto.parentDocumentId = entity.parentDocumentId;
    dto.folderPath = entity.folderPath;
    dto.description = entity.description;
    dto.content = entity.content;
    dto.contentSummary = entity.contentSummary;
    dto.tags = entity.tags;
    dto.labels = entity.labels;
    dto.customFields = entity.customFields;
    dto.documentStatus = entity.documentStatus;
    dto.documentStage = entity.documentStage;
    dto.ownerId = entity.ownerId;
    dto.organizationId = entity.organizationId;
    dto.isPublic = entity.isPublic;
    dto.isShared = entity.isShared;
    dto.sharingEnabled = entity.sharingEnabled;
    dto.templateId = entity.templateId;
    dto.entityType = entity.entityType;
    dto.entityId = entity.entityId;
    dto.storageProvider = entity.storageProvider;
    dto.storageLocation = entity.storageLocation;
    dto.isEncrypted = entity.isEncrypted;
    dto.isPasswordProtected = entity.isPasswordProtected;
    dto.isIndexed = entity.isIndexed;
    dto.metadata = entity.metadata;
    dto.createdAt = entity.createdAt;
    dto.updatedAt = entity.updatedAt;
    dto.createdBy = entity.createdBy;
    dto.updatedBy = entity.updatedBy;
    return dto;
  }
}
